version: '2'

services:

  node-service:
    container_name: dym-node-container
    image: dym-node-image
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    entrypoint: /var/www/docker/node/start.sh
    depends_on:
      - mysql-service
    volumes:
      - ./:/var/www/html
      - composer:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    ports:
      - "3000:3000"
    networks:
      - default

  laravel-service:
    container_name: dym-laravel-container
    image: dym-laravel-image
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    entrypoint: /var/www/docker/laravel/start.sh
    depends_on:
      - mysql-service
      - node-service
    environment:
      DB_HOST: mysql-service
      DB_DATABASE: docker
      DB_USERNAME: root
      DB_PASSWORD: docker
    volumes:
      - ./:/var/www/html
      - composer:/var/www/html/vendor
    ports:
      - "80:80"
    networks:
      - default

  mysql-service:
    container_name: dym-mysql-container
    image: dym-mysql-image
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    # volumes:
    #   - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - "3306:3306"
    networks:
      - default

  phpmyadmin:
    container_name: dym-phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-service:mysql
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-service
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=docker
    depends_on:
      - mysql-service
    networks:
      - default

volumes:
  composer:
  node_modules:
networks:
  default: