# Cloud66 service settings
version: 2
services:
  laravel-service:
    git_url: git@bitbucket.org:defendyourmoney/defendyourmoney-laravel-vue.git
    git_branch: master
    ports:
    - 80:80
    command: "/var/www/docker/laravel/production/start.sh"
    use_habitus: true
    use_habitus_step: laravel-production-service
    health:
      ready:
        type: http
        endpoint: "/"
        protocol: http
        timeout: 300
        initial_delay: 2